export const listedStates = [
  { id: 1, stateName: 'Alabama', unavailable: false },
  { id: 2, stateName: 'Alaska', unavailable: false },
  { id: 3, stateName: 'Arizona', unavailable: false },
  { id: 4, stateName: 'Arkansas', unavailable: false },
  { id: 5, stateName: 'California', unavailable: false },
  { id: 6, stateName: 'Colorado', unavailable: false },
  { id: 7, stateName: 'Connecticut', unavailable: false },
  { id: 8, stateName: 'Delaware', unavailable: false },
  { id: 9, stateName: 'Florida', unavailable: false },
  { id: 10, stateName: 'Georgia', unavailable: false },
  { id: 11, stateName: 'Hawaii', unavailable: false },
  { id: 12, stateName: 'Idaho', unavailable: false },
  { id: 13, stateName: 'Illinois', unavailable: false },
  { id: 14, stateName: 'Indiana', unavailable: false },
  { id: 15, stateName: 'Iowa', unavailable: false },
  { id: 16, stateName: 'Kansas', unavailable: false },
  { id: 17, stateName: 'Kentucky', unavailable: false },
  { id: 18, stateName: 'Louisiana', unavailable: false },
  { id: 19, stateName: 'Maine', unavailable: false },
  { id: 20, stateName: 'Maryland', unavailable: false },
  { id: 21, stateName: 'Massachusetts', unavailable: false },
  { id: 22, stateName: 'Michigan', unavailable: false },
  { id: 23, stateName: 'Minnesota', unavailable: false },
  { id: 24, stateName: 'Mississippi', unavailable: false },
  { id: 25, stateName: 'Missouri', unavailable: false },
  { id: 26, stateName: 'Montana', unavailable: false },
  { id: 27, stateName: 'Nebraska', unavailable: false },
  { id: 28, stateName: 'Nevada', unavailable: false },
  { id: 29, stateName: 'New Hampshire', unavailable: false },
  { id: 30, stateName: 'New Jersey', unavailable: false },
  { id: 31, stateName: 'New Mexico', unavailable: false },
  { id: 32, stateName: 'New York', unavailable: false },
  { id: 33, stateName: 'North Carolina', unavailable: false },
  { id: 34, stateName: 'North Dakota', unavailable: false },
  { id: 35, stateName: 'Ohio', unavailable: false },
  { id: 36, stateName: 'Oklahoma', unavailable: false },
  { id: 37, stateName: 'Oregon', unavailable: false },
  { id: 38, stateName: 'Pennsylvania', unavailable: false },
  { id: 39, stateName: 'Rhode Island', unavailable: false },
  { id: 40, stateName: 'South Carolina', unavailable: false },
  { id: 41, stateName: 'South Dakota', unavailable: false },
  { id: 42, stateName: 'Tennessee', unavailable: false },
  { id: 43, stateName: 'Texas', unavailable: false },
  { id: 44, stateName: 'Utah', unavailable: false },
  { id: 45, stateName: 'Vermont', unavailable: false },
  { id: 46, stateName: 'Virginia', unavailable: false },
  { id: 47, stateName: 'Washington', unavailable: false },
  { id: 48, stateName: 'West Virginia', unavailable: false },
  { id: 49, stateName: 'Wisconsin', unavailable: false },
  { id: 50, stateName: 'Wyoming', unavailable: false },
]
